#!/usr/bin/env bash
# SSH client configuration
#
Host *
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
    sendEnv LANG LC_*
    HashKnownHosts ys
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
